### ISSUE TITLE
Indivio.us main instance shutdown. Suggestions.

### ISSUE THREAD

**Issue by CaioCMartinelli** [kubuzetto/ytlc#1]
As invidio.us shut down and the alternative instances are kind of unstable, I was wondering, would it be possible to use 4 or 5 of them as one at the same time?

I took the code and changed the URL's to create 5 different extensions, each accessing a different instance to deal with the instability, the problem is that sometimes different texts overlap each other.

An alternative would be to use personal google API key again, would it be possible without the limit of 100 of the old versions from 2018?

For me this is one of the best extensions I have ever installed, it makes the YT experience much better. Do you think you're still going to work on it?

Thanks man

**Comment by kubuzetto** [comment]
> As invidio.us shut down

Damn, that's really sad news. invidio.us API was both much easier to use than YT API, and was publicly available. It was a delight to work with.

I like this add-on too, and I would love to work on it; but to be frank at this point I've promised to many people that I'd make the API access part optional, and I just seem to not be able to find time for it. I'm in the middle of changing jobs, and even though I can still work on [my other add-on](https://github.com/kubuzetto/behind) (it has a cleaner code and fixes are generally very localized on that one: _change one line and it works again_), I'd have to invest some time on this one to make it work.

If you are willing, I'd love accepting PRs on it. Otherwise, I really want to fix it, but I also cannot promise a time frame to make it functional again.

**Comment by kubuzetto** [comment]
Hey @CaioCMartinelli, I just merged the old YouTube API fetch code into the latest code. It's a frantic, last-minute, hacky fix, but at least the add-on should keep working for a while longer.

Can you please give it a try and comment on this issue so that I can close it?

**Comment by CaioCMartinelli** [comment]
>I like this add-on too, and I would love to work on it; but to be frank at this point I've promised to many people that I'd make the API access part optional, and I just seem to not be able to find time for it. I'm in the middle of changing jobs, and even though I can still work on my other add-on (it has a cleaner code and fixes are generally very localized on that one: change one line and it works again), I'd have to invest some time on this one to make it work.

Ah ok, I see, changing jobs really is complicated, especially in the beginning.
 
 
>If you are willing, I'd love accepting PRs on it. Otherwise, I really want to fix it, but I also cannot promise a time frame to make it functional again.`

I'll try, the problem is that professionally I'm a civil project engineer, I only know the basics of programming, I do more for fun. If I get something with regard to the extension I will be happy to pass to you.
 
 
>Hey @CaioCMartinelli, I just merged the old YouTube API fetch code into the latest code. It's a frantic, last-minute, hacky fix, but at least the add-on should keep working for a while longer.`
 
 
Ok, ill test it, but with "YouTube API fetch code into the latest code" do you mean it is possible to have more than 100 results?

Thanks man

**Comment by CaioCMartinelli** [comment]
Hi @kubuzetto 

From my tests: In general it is working fine again, the only thing is that the number of results are now very limited.

(The test was based on a comparison with 5 simultaneous extensions of alternative instances of the invidious that I mentioned earlier)

I think you can close this, if i manage to do something i will let you know.
